from __future__ import annotations

from pathlib import Path


RL_BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = RL_BASE_DIR.parent
PREDICTIVE_BASE_DIR = PROJECT_ROOT / "predictive-resource"
PREDICTIVE_SCRIPTS_DIR = PREDICTIVE_BASE_DIR / "scripts"
PREDICTIVE_RESULTS_DIR = PREDICTIVE_BASE_DIR / "results"
PREDICTIVE_RUN_HYBRID = PREDICTIVE_SCRIPTS_DIR / "run_hybrid.py"

DATA_DIR = RL_BASE_DIR / "data"
INPUT_DIR = DATA_DIR / "input"
REFERENCE_DIR = DATA_DIR / "reference"
OUTPUT_DIR = DATA_DIR / "output"
RESULTS_DIR = RL_BASE_DIR / "results"
ARTIFACT_DIR = RL_BASE_DIR / "artifacts"

for path in (INPUT_DIR, REFERENCE_DIR, OUTPUT_DIR, RESULTS_DIR, ARTIFACT_DIR):
    path.mkdir(parents=True, exist_ok=True)

ACTUAL_TRAFFIC_CSV = INPUT_DIR / "sale_event_traffic.csv"
FORECAST_TRAFFIC_CSV = INPUT_DIR / "predicted_traffic.csv"
REFERENCE_PLAN_CSV = REFERENCE_DIR / "resource_allocation_plan.csv"
REFERENCE_LOADGEN_CSV = REFERENCE_DIR / "loadgen_result.csv"
REFERENCE_CORRECTION_CSV = REFERENCE_DIR / "hybrid_correction_log.csv"
RUNTIME_ALLOC_LOG_CSV = OUTPUT_DIR / "rl_predictive_allocation_log.csv"
RUNTIME_CORRECTION_LOG_CSV = OUTPUT_DIR / "rl_hybrid_correction_log.csv"
RUNTIME_LOADGEN_CSV = OUTPUT_DIR / "rl_loadgen_result.csv"
RUNTIME_PREDICTED_CSV = OUTPUT_DIR / "rl_predicted_traffic.csv"

TRAINED_MODEL_PATH = ARTIFACT_DIR / "ppo_resource_agent.zip"
EVAL_SUMMARY_PATH = OUTPUT_DIR / "rl_eval_summary.json"
RL_PLAN_PATH = OUTPUT_DIR / "rl_resource_allocation_plan.csv"
TRAINING_CURVE_PATH = RESULTS_DIR / "rl_training_curve.png"
EVAL_PLOT_PATH = RESULTS_DIR / "rl_eval_plots.png"

# RL action space
ACTION_HOLD = 0
ACTION_CPU_UP = 1
ACTION_CPU_DOWN = 2
ACTION_REP_UP = 3
ACTION_REP_DOWN = 4
ACTION_CPU_AND_REP_UP = 5
ACTION_NAMES = {
    ACTION_HOLD: "HOLD",
    ACTION_CPU_UP: "CPU_UP",
    ACTION_CPU_DOWN: "CPU_DOWN",
    ACTION_REP_UP: "REP_UP",
    ACTION_REP_DOWN: "REP_DOWN",
    ACTION_CPU_AND_REP_UP: "CPU_AND_REP_UP",
}

# resource bounds
MIN_CPU = 2.0
MAX_CPU = 6.0
CPU_STEP = 0.5
MIN_REPLICAS = 3
MAX_REPLICAS = 7

# latency/SLA configuration
SLA_LATENCY_MS = 1000.0
LOOKAHEAD_WINDOW = 30
WARMUP_PENALTY_STEPS = 5
WARMUP_LATENCY_MS = 120.0
WARMUP_P95_MS = 220.0

# simulator capacity assumption
CPU_CAPACITY_POLICY = {
    2.0: 55.0,
    2.5: 67.5,
    3.0: 80.0,
    3.5: 92.5,
    4.0: 105.0,
    4.5: 117.5,
    5.0: 130.0,
    5.5: 142.5,
    6.0: 155.0,
}

# reward weights
FAIL_PENALTY = 20.0
SLA_PENALTY = 8.0
AVG_LATENCY_PENALTY = 0.020
P95_LATENCY_PENALTY = 0.050
CPU_COST_PENALTY = 0.18
REPLICA_COST_PENALTY = 0.45
SUCCESS_REWARD = 0.02
UNDER_SLA_BONUS = 2.0
LOW_TAIL_BONUS = 1.5
PEAK_PROTECTION_BONUS = 2.0
PEAK_BONUS_THRESHOLD_RPS = 500.0
PEAK_CPU_COST_MULTIPLIER = 0.75
PEAK_REPLICA_COST_MULTIPLIER = 0.75
NON_PEAK_CPU_COST_MULTIPLIER = 1.10
NON_PEAK_REPLICA_COST_MULTIPLIER = 1.15
IDLE_RPS_THRESHOLD = 250.0
IDLE_PREDICTED_RPS_THRESHOLD = 300.0
IDLE_HIGH_REPLICA_THRESHOLD = 6
IDLE_HIGH_CPU_THRESHOLD = 5.0
IDLE_RESOURCE_PENALTY = 4.5
NON_PEAK_UPSCALE_PENALTY = 0.6
SCALE_DOWN_STABLE_BONUS = 1.8
SCALE_DOWN_CPU_BONUS = 0.4
SCALE_DOWN_REPLICA_BONUS = 0.7
SCALE_DOWN_MAX_AVG_LATENCY_MS = 650.0
SCALE_DOWN_MAX_P95_MS = 900.0
TEACHER_CPU_DISTANCE_PENALTY = 0.45
TEACHER_REPLICA_DISTANCE_PENALTY = 0.90
TEACHER_ALIGNMENT_BONUS = 1.5
TEACHER_PEAK_ALIGNMENT_BONUS = 1.0
STEP_CHANGE_PENALTY = 0.35

# planning/export smoothing
MIN_PLAN_HOLD_STEPS = 3

# training defaults
DEFAULT_TOTAL_TIMESTEPS = 50_000
DEFAULT_SEED = 42
CURRICULUM_STAGES = [
    ("easy", 0.20),
    ("peak", 0.30),
    ("full", 0.50),
]
